// <auto-generated />
using System;
using EasyParking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyParking.Data.Migrations
{
    [DbContext(typeof(EasyParkingDbContext))]
    partial class EasyParkingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("EasyParking.Domain.Entities.Dauermieter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FesterParkplatzId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Gesperrt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ParkhausId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("FesterParkplatzId")
                        .IsUnique();

                    b.HasIndex("ParkhausId");

                    b.ToTable("Dauermieter");
                });

            modelBuilder.Entity("EasyParking.Domain.Entities.Feiertag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParkhausId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParkhausId");

                    b.HasIndex("Datum", "ParkhausId");

                    b.ToTable("Feiertage");
                });

            modelBuilder.Entity("EasyParking.Domain.Entities.Mietzahlung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Betrag")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("DauermieterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Jahr")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Monat")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Zahldatum")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DauermieterId");

                    b.ToTable("Mietzahlungen");
                });

            modelBuilder.Entity("EasyParking.Domain.Entities.Parkhaus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gruppe")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Stadt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Parkhaeuser");
                });

            modelBuilder.Entity("EasyParking.Domain.Entities.Parkplatz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DauermieterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nummer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockwerkId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Typ")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StockwerkId");

                    b.ToTable("Parkplaetze");
                });

            modelBuilder.Entity("EasyParking.Domain.Entities.Parkticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AusgangsZeit")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Betrag")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Bezahlt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DauermieterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EingangsZeit")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kategorie")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParkhausId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParkplatzId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TicketNummer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DauermieterId");

                    b.HasIndex("ParkhausId");

                    b.HasIndex("ParkplatzId");

                    b.HasIndex("TicketNummer")
                        .IsUnique();

                    b.ToTable("Parktickets");
                });

            modelBuilder.Entity("EasyParking.Domain.Entities.Stockwerk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Nummer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParkhausId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParkhausId");

                    b.ToTable("Stockwerke");
                });

            modelBuilder.Entity("EasyParking.Domain.Entities.Tarif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndStunde")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParkhausId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PreisProStunde")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("StartStunde")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Typ")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParkhausId");

                    b.ToTable("Tarife");
                });

            modelBuilder.Entity("EasyParking.Domain.Entities.Dauermieter", b =>
                {
                    b.HasOne("EasyParking.Domain.Entities.Parkplatz", "FesterParkplatz")
                        .WithOne("Dauermieter")
                        .HasForeignKey("EasyParking.Domain.Entities.Dauermieter", "FesterParkplatzId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EasyParking.Domain.Entities.Parkhaus", "Parkhaus")
                        .WithMany("Dauermieter")
                        .HasForeignKey("ParkhausId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FesterParkplatz");

                    b.Navigation("Parkhaus");
                });

            modelBuilder.Entity("EasyParking.Domain.Entities.Feiertag", b =>
                {
                    b.HasOne("EasyParking.Domain.Entities.Parkhaus", "Parkhaus")
                        .WithMany()
                        .HasForeignKey("ParkhausId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Parkhaus");
                });

            modelBuilder.Entity("EasyParking.Domain.Entities.Mietzahlung", b =>
                {
                    b.HasOne("EasyParking.Domain.Entities.Dauermieter", "Dauermieter")
                        .WithMany("Mietzahlungen")
                        .HasForeignKey("DauermieterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dauermieter");
                });

            modelBuilder.Entity("EasyParking.Domain.Entities.Parkplatz", b =>
                {
                    b.HasOne("EasyParking.Domain.Entities.Stockwerk", "Stockwerk")
                        .WithMany("Parkplaetze")
                        .HasForeignKey("StockwerkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stockwerk");
                });

            modelBuilder.Entity("EasyParking.Domain.Entities.Parkticket", b =>
                {
                    b.HasOne("EasyParking.Domain.Entities.Dauermieter", "Dauermieter")
                        .WithMany()
                        .HasForeignKey("DauermieterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EasyParking.Domain.Entities.Parkhaus", "Parkhaus")
                        .WithMany("Parktickets")
                        .HasForeignKey("ParkhausId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EasyParking.Domain.Entities.Parkplatz", "Parkplatz")
                        .WithMany()
                        .HasForeignKey("ParkplatzId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dauermieter");

                    b.Navigation("Parkhaus");

                    b.Navigation("Parkplatz");
                });

            modelBuilder.Entity("EasyParking.Domain.Entities.Stockwerk", b =>
                {
                    b.HasOne("EasyParking.Domain.Entities.Parkhaus", "Parkhaus")
                        .WithMany("Stockwerke")
                        .HasForeignKey("ParkhausId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parkhaus");
                });

            modelBuilder.Entity("EasyParking.Domain.Entities.Tarif", b =>
                {
                    b.HasOne("EasyParking.Domain.Entities.Parkhaus", "Parkhaus")
                        .WithMany("Tarife")
                        .HasForeignKey("ParkhausId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parkhaus");
                });

            modelBuilder.Entity("EasyParking.Domain.Entities.Dauermieter", b =>
                {
                    b.Navigation("Mietzahlungen");
                });

            modelBuilder.Entity("EasyParking.Domain.Entities.Parkhaus", b =>
                {
                    b.Navigation("Dauermieter");

                    b.Navigation("Parktickets");

                    b.Navigation("Stockwerke");

                    b.Navigation("Tarife");
                });

            modelBuilder.Entity("EasyParking.Domain.Entities.Parkplatz", b =>
                {
                    b.Navigation("Dauermieter");
                });

            modelBuilder.Entity("EasyParking.Domain.Entities.Stockwerk", b =>
                {
                    b.Navigation("Parkplaetze");
                });
#pragma warning restore 612, 618
        }
    }
}
